ModificationType: Mod
Name: C&C Power Play
Version: 1.1
SimpleDownloadLink: https://onedrive.live.com/embed?cid=1E884F024F359EC2&resid=1E884F024F359EC2%212234&authkey=AO1iRVgABXSnjWI
UIImageSourceLink: https://i.imgur.com/T1eOEiF.png
ModDBLink: https://www.moddb.com/mods/cc-power-play
NewsLink: https://www.moddb.com/mods/cc-power-play/articles
DependenceName: ''
S3HostLink: gen.insave.ovh:9000
S3BucketName: cncpowerplay
S3FolderName: modfiles
S3HostPublicKey: ''
S3HostSecretKey: ''